import Head from "next/head";
import Link from "next/link";
import React from "react";

const Layout = ({ user, children }): any => {
  return (
    <>
      <Head>
        <title>Leroy merlin cours de Bricolage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <nav>
        <div className="navBar">
          <div>
            <Link href="/">
              <a>
                <img
                  className="logo"
                  src="/images/LogoLM.png"
                  alt="logo leroy merlin"
                />
              </a>
            </Link>
          </div>
          <div className="navButtons">
            <div>
              <p>Welcome {user?.name}</p>
            </div>

            <div>
              {user ? (
                <Link href="/api/auth/logout" passHref={true}>
                  <a>Deconnection</a>
                </Link>
              ) : (
                <Link href="/api/auth/login" passHref={true}>
                  <a>Se connecter</a>
                </Link>
              )}

              {user ? (
                <Link href="/profil" passHref={true}>
                  <a>Profil</a>
                </Link>
              ) : null}
              {user ? (
                <Link href="/cartStore" passHref={true}>
                  <a>Panier</a>
                </Link>
              ) : null}
            </div>
          </div>
        </div>
      </nav>

      <div className="banner">
        <h1>titre</h1>
        <span className="underline"></span>
      </div>
      <div>{children}</div>
      <footer>
        <div className="flexFooter">
          <div>
            <p>Tuto en ligne</p>
            <ul>
              <li>
                <Link href="/onlinestore/Plomberie">
                  <a>Plomberie</a>
                </Link>
              </li>
              <li>
                <Link href="/onlinestore/Electricité">
                  <a>Electricité</a>
                </Link>
              </li>
              <li>
                <Link href="/onlinestore/Peinture">
                  <a>Peinture</a>
                </Link>
              </li>
              <li>
                <Link href="/onlinestore/Sol">
                  <a>Sol</a>
                </Link>
              </li>
            </ul>
          </div>
          <div>
            <p>Cours en magasin</p>
            <ul>
              <li>
                <Link href="/store/Plomberie">
                  <a>Plomberie</a>
                </Link>
              </li>
              <li>
                <Link href="/store/Electricité">
                  <a>Electricité</a>
                </Link>
              </li>
              <li>
                <Link href="/store/Peinture">
                  <a>Peinture</a>
                </Link>
              </li>
              <li>
                <Link href="/store/Sol">
                  <a>Sol</a>
                </Link>
              </li>
            </ul>
          </div>
          <div>
            <p>Contact</p>
            <ul>
              <li>
                <Link href="/onlinestore/contact">
                  <a>Service client</a>
                </Link>
              </li>
              <li>
                <Link href="/onlinestore/profil">
                  <a>Mon compte</a>
                </Link>
              </li>
              <li>
                <Link href="/onlinestore/contact">
                  <a>Téléphone</a>
                </Link>
              </li>
              <li>
                <Link href="/onlinestore/contact">
                  <a>Mail</a>
                </Link>
              </li>
            </ul>
          </div>

          <div className="footerRS">
            <ul>
              <li>
                <Link
                  href={"https://www.facebook.com/leroymerlin?ref=ts&fref=ts"}
                >
                  <img
                    className="footerLogo"
                    src="/images/facebook.png"
                    alt="lien facebook"
                  />
                </Link>
              </li>
              <li>
                <Link href="https://www.instagram.com/leroymerlin/">
                  <img
                    className="footerLogo"
                    src="/images/instagram.png"
                    alt="lien instagram"
                  />
                </Link>
              </li>
              <li>
                <Link href="https://www.linkedin.com/company/leroy-merlin?originalSubdomain=fr">
                  <img
                    className="footerLogo"
                    src="/images/linkedin.png"
                    alt="lien linkedin"
                  />
                </Link>
              </li>
              <li>
                <Link href="https://www.pinterest.fr/leroymerlinfr/">
                  <img
                    className="footerLogo"
                    src="/images/pinterest.png"
                    alt="lien pinterest"
                  />
                </Link>
              </li>
              <li>
                <Link href="https://twitter.com/leroymerlinfr">
                  <img
                    className="footerLogo"
                    src="/images/twitter.png"
                    alt="lien twitter"
                  />
                </Link>
              </li>
              <li>
                <Link href="https://www.youtube.com/user/leroymerlinfr">
                  <img
                    className="footerLogo"
                    src="/images/youtube.png"
                    alt="lien youtube"
                  />
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </footer>
      <p className="copyright">
        Le contenu de ce site est protégé par la loi du copyright et appartient
        à LeroyMerlin
      </p>
    </>
  );
};

export default Layout;
