import Head from "next/head";
import Link from "next/link";
import React from "react";
import Image from "next/image";
import { UserProvider, useUser } from "@auth0/nextjs-auth0";

const Layout = ({ user }): any => {
  if (user) {
    return (
      <>
        <Head>
          <title>Leroy merlin cours de Bricolage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <nav>
          <div className="container">
            <div className="Element1">
              <Image
                width={150}
                height={100}
                src="/images/logoCampus.png"
                alt="logoCampus.png"
              />
            </div>

            <Link href="/" passHref={true}>
              <button>Home</button>
            </Link>
            <Link href="/store" passHref={true}>
              <button>Mon magasin</button>
            </Link>
            <Link href="/profil" passHref={true}>
              <button>Mon Profil</button>
            </Link>

            <Link href="/api/auth/logout" passHref={true}>
              <button>Se déconnecter</button>
            </Link>
            <Link href="/cartStore" passHref={true}>
              <button>Panier</button>
            </Link>
          </div>
        </nav>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Leroy merlin cours de Bricolage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <nav>
          <div className="container">
            <div className="Element1">
              <Image
                width={150}
                height={100}
                src="/images/logoCampus.png"
                alt="logoCampus.png"
              />
            </div>

            <Link href="/" passHref={true}>
              <button>Home</button>
            </Link>
            <Link href="/store" passHref={true}>
              <button>Mon magasin</button>
            </Link>
            <Link href="/api/auth/login" passHref={true}>
              <button>Se connecter</button>
            </Link>

            <Link href="/cartStore" passHref={true}>
              <button>Panier</button>
            </Link>
          </div>
        </nav>
      </>
    );
  }
};

export default Layout;
